name: ${plugin.name}
main: space.arim.perms.spigot.ArimPermsSpigot
version: ${plugin.version}
author: ${plugin.author}
website: ${plugin.url}
description: ${plugin.description}
depend: [ArimAPI]

commands:
  arimperms:
    description: Everything related to ArimPerms
    aliases: ap
    usage: /arimperms <arguments>