storage:
  mode: 'file'
  mysql:
    table-prefix: 'arimperms_'
    host: 'localhost'
    port: 3306
    database: 'permissions'
    username: 'ArimPerms'
    password: 'defaultpassword'
    url: 'jdbc:mysql://%HOST%:%PORT%/%DATABASE%?autoReconnect=true&useUnicode=true&characterEncoding=utf8'
groups-on-first-join:
  - 'default'