storage:
  mode: 'file'
  mysql:
    table-prefix: 'arimperms_'
    host: 'localhost'
    port: 3306
    database: 'permissions'
    username: 'ArimPerms'
    password: 'defaultpassword'
    url: 'jdbc:mysql://%HOST%:%PORT%/%DATABASE%?autoReconnect=true&useUnicode=true&characterEncoding=utf8'
add-groups-on:
  join:
    - 'default'
  first-join:
    - 'default'
bad-plugins:
  fail-gracefully: true
  stringly-players:
    enable-compatibility: true
    log-calls:
      enable: true
      log-caller-class: false
do-not-touch-version: 1